### ISSUE TITLE
quescied backup

### ISSUE THREAD

**Issue by buzzzo** [NAUbackup/VmBackup#21]
why the quiescied backup is not implemented ?

**Comment by NAUbackup** [comment]
Sorry, but am not sure what you mean by a quiescied backed -- do you mean if the VM is not running, or what exactly? Any VM that is possible to take a snapshot of should be able to be backed up, whether running or not.

**Comment by buzzzo** [comment]
I mean:  xe vm-snapshot-with-quiesce
In essence: request to a windows vm to do a vss snapshot BEFORE taking the snapshot.
This helps in case like sql server and something like that to have a much more consistent snapshot 

Read this: https://discussions.citrix.com/topic/350874-what-is-a-quiesced-snapshot-vs-a-standard-snapshot/

**Comment by davisko** [comment]
I would recommend putting the DB data directory (where the .mdf files are) on a separate virtual drive. Then use NAUbackup vdi snapshot method to capture the system drive, but not the data drive. SQL server has robust backup options built in, which can be used to backup the data files. Disk or VM snapshots really aren't the best way to backup DB data...

**Comment by buzzzo** [comment]
Davisko this is the current implementation. Since the mod to the code is trivial having a plain and compliant xenserver way to do a full consistent vss aware backup would be a must or at least a nice to have.

**Comment by NAUbackup** [comment]
The latest version allows for just backing up the primary (first) drive, so you could do just the OS partition separately using the utility's vdi-export mechanism.

**Comment by buzzzo** [comment]
Yes but how this is related with my topic ?

**Comment by NAUbackup** [comment]
Sorry, that reply was intended for a different thread.  The implementation would involve either a separate flag or group to track this. Other than your request, this has not been requested by others. We have very limited resources since some internal personnel restructuring, so cannot possibly get to all features, but will bear this in mind for th efuture. We are currently focused on incorporating regex to be able to select which VMs to backup.
