### ISSUE TITLE
BUG - XenServer 7.3 No such directory /snapshots/

### ISSUE THREAD

**Issue by MikeDombo** [NAUbackup/VmBackup#66]
I'm running XenServer 7.3 and there is no /snapshots/ directory, so the backup script fails looking for /snapshots/NAUbackup/status.log.

Please, is there a fix for 7.3?

**Comment by NAUbackup** [comment]
Hi, Mike:
The documentation indicates this is how it's defined as shipped, so you can either (1) create a /snapshots/NAUback directory and subdirectory, or (2) edit the configuration to make use of a different directory. This is deliberate, so as not to pollute the XenServer area itself unexpectedly with a lot of data that would otherwise quickly eat up the available space on dom0 and bring the server to a halt.

If you have ideas as to how this could be documented better, we're happy to take suggestions.
Let us know if you have any other questions.

Regards,
--Tobias

**Comment by MikeDombo** [comment]
Whoops, you are totally right!
The included example.cfg omits the status_path option that is described in the readme. Setting that option did fix my problem.

**Comment by NAUbackup** [comment]
Glad that's taken care of -- maybe we should add a comment in the example.cfg file left comment out?

**Comment by MikeDombo** [comment]
I think that would be a good idea since it is in the README, but I just downloaded the example cfg and modified that. Also, it would be extra nice if it didn't crash when it can't find the file. Instead it should offer to create the directory or quit when it doesn't exist.

**Comment by NAUbackup** [comment]
Good idea, Mike, regarding a check and clean exit upon failure. I will work on that and get out an updated release ASAP. The script should check for the presence of the directory and whether it's also writable.

--Tobias
