### ISSUE TITLE
verify_vm_name: ERROR more than one vm with the name ...

### ISSUE THREAD

**Issue by AlBundyLoves69** [NAUbackup/VmBackup#73]
Very strange:

I received the error `verify_vm_name: ERROR more than one vm with the name AAEB-DEV202WD` but there is **only one VM with this name**. How comes?

All other VMs have been processed without any problem.

**Comment by AlBundyLoves69** [comment]
I was now investigating it and the reason was that this VM had a snapshot. Once I deleted the snapshot then it worked. Strange. I didn't find anything in the Readme file regarding snapshots issues...

**Comment by NAUbackup** [comment]
Hi, Al... That is odd, as there should be no restriction unless the number of supported snapshots (around 30) is exceeded or there was some error with that existing snapshot. When I get a chance, I will try taking a snapshot and then running a backup to see if this can be replicated.

Please not also and suggestions for improvement or submitted code modifications will certainly be taken into consideration!

Thank you,
--Tobias

**Comment by AlBundyLoves69** [comment]
Here you post the screenshot from XenCenter where you can see that I deleted this snapshot and what its name was.

Really very strange, I neither could believe it - I was just trying something because I didn't understand the error message and this was the only one difference to the other VMs.

![image](https://user-images.githubusercontent.com/9625486/39099691-f5bd6fba-467e-11e8-94f1-35df033b1c58.png)

**Comment by AlBundyLoves69** [comment]
**I can now reproduce it any time I want :-):**

>2018-04-23-(11:59:37) - verify_vm_name: ERROR more than one vm with the name AAEB-DEV202WD

Snapshots content:

![grafik](https://user-images.githubusercontent.com/9625486/39120185-06e0040a-46ee-11e8-9d05-7de57768aa93.png)

This happens **only when a snapshot has exactly the same name as the VM does.** I hope this helps you now.

The email content:

> 2018/04/23 11:59:36,vmbackup.py,AAEB91,begin
> 2018/04/23 11:59:37,vm-export,AAEB91,begin,AAEB-DEV202WD
> 2018/04/23 11:59:37,vm-export,AAEB91,end,ERROR verify_vm_name AAEB-DEV202WD
> 2018/04/23 11:59:37,vmbackup.py,AAEB91,end,ERROR,S:0 W:0 E:1
>

**Comment by AlBundyLoves69** [comment]
Have a look how it can happen the snapshot has the same name as the VM:

![grafik](https://user-images.githubusercontent.com/9625486/39144876-6945c3a2-4732-11e8-9f99-439a73b56604.png)

I just enter it in the `Name` field.

**Comment by NAUbackup** [comment]
Why in the world would you ever name a snapshot exactly the same as a VM? That said, I do agree it should still not bomb like it does!

**Comment by NAUbackup** [comment]
Or, what I'm guessing, is that the UUID should be used if possible instead of the name label, which is the one thing that should be totally unique. The problem is that the script depends on the names, as is the most convenient way to do this and would be a major effort to rework.

BTW, if you do a "preview" I'm guessing this error won't show up, correct, Peter?

Not sure what you mean by incremented by one, but I'd have to look at the code probably first to get a better idea. There is then also the danger of potentially grabbing the wrong instance, which would also have to be taken into account.

--Tobias

**Comment by AlBundyLoves69** [comment]
I understand the problem regarding the UUID and the name.

I meant this:
```
def verify_vm_name(tmp_vm_name):
    vm = session.xenapi.VM.get_by_name_label(tmp_vm_name)
# if the snapshot has the same name then the check should be  if (len(vm) > 2):
    if (len(vm) > 1):
        return 'ERROR more than one vm with the name %s' % tmp_vm_name
    elif (len(vm) == 0):
        return 'ERROR no machines found with the name %s' % tmp_vm_name
    return vm[0]
```

And yes, of course in the preview there is no issue. But run it and it will trigger immediately the error - so it is nice to _test/fix it_ because you don't have to wait too long.

**Comment by NAUbackup** [comment]
I also just found an unusual case where a VM name is to be excluded that doesn't exist, and needs to be trapped. Hopefully, I can get an update out fairly soon that deals with all these collected issues. Bugs need to get more attention than features.

Also to clarify above, Peter, if the length of the VM is >1 it should also trap the case of it being 2 or more, so are you saying it's still not catching the snapshot with the same name condition? I guess I could create one and check what the output is of the length check.

**Comment by AlBundyLoves69** [comment]
I have an idea. Let me check it out. Write here you know I read your message and I am working on it.

**Comment by NAUbackup** [comment]
Peter, good point.  The intention is to use system calls as little as possible, but there are still some like "ls" so that's not even a totally valid argument. Could say the same about listing VDIs, I suppose.
And, yes, someone might name two VMs the same, but that at lest should get flagged. I'll ponder this some more -- thanks for your input! It coul dbe done with "xe vm-list params=name-label" One cannot possible prevent human errors from messing things up.
As mentioned earlier in a discussion, one option would be to convert everything to UUIDs, but that would be a lot of extra work and way less transparent.

**Comment by NAUbackup** [comment]
Just reviewed the code and there are a number of places where "xe vm-list" and "xe vdi-list" are utilized, so I will rethink the VM checking mechanism; should be a pretty easy substitute, and thanks again for your input, Peter! The xe command is pretty efficient and even if run hundreds of times, isn't going to slow things down any sort of appreciable amount.
--Tobias

**Comment by NAUbackup** [comment]
Part of the challenge is that the thorough search for duplicates doesn't currently exist in the preview section, which it ought to. Will have to think about that some more. Checking for duplicates in the running procedure is straight-forward.

**Comment by AlBundyLoves69** [comment]
Tobias, I follow in my scripts the fact, that the script is not executed by idiots. I check some general conditions because we are all human and we can make mistakes, but I don't check all possible constellations.

Here it is the same. Your backup script supposes that on the host don't exist VMs with the same name even the ID is different. As your colleague explained in a post, to change the script using the IDs would break the whole script I don't see the need to change the internal logic.

I would solve it that way that the script performs a _pre-check_ to assure the host doesn't have duplicate VM names. No discussion, no hard feelings. This is a condition which must be met in order to use your script.

**Comment by NAUbackup** [comment]
Peter,
I agree. I'm getting closer with a pre-check option that I think I can build in and also as a fail condition if encountered should one still decide to try to run the script by force. People do make mistakes and things happen that are sometimes outside of one's own control.

My feeling is if it finds a duplicate name, it should fail, since it's too risky to overwrite something that may already exist that may be a completely different VM. BTW, the "colleague" explaining using the UUID would be hard to do was actually also me! :-)
 
I am all for sanity checks. It just gets harder to make comprehensive changes as code expands as in some cases, building things in retroactively just makes for spaghetti code.

Best,
--Tobias

**Comment by NAUbackup** [comment]
Here is a workarounf for now that goes in after the "all_
    
    # init vm-export/vdi-export/exclude in config list
    config['vm-export'] = []
    config['vdi-export'] = []
    config['exclude'] = []
    warning_match = False
    error_regex = False

    all_vms = get_all_vms()
    #-------------------------------BEGIN NEW CODE--------------
    ## pre-check here for any duplicate VMs
    ### print "CHECK got all Vms"
    for vm in all_vms:
       #print "DEBUG vm name= %s" % vm
       cmd = '%s/xe vm-list name-label="%s" --minimal | /bin/grep ","' % (xe_path, vm)
       #print "DEBUG - test for duplicate %s" % cmd
       res = run_get_lastline(cmd)
       #print 'DEBUG cmd-output for res= %s' % res
       if (len(res) > 0):
          print '*** FATAL ERROR - DEBUG333 more than one VM with the name %s' % vm
          sys.exit(1)
          #-------------------------------END NEW CODE--------------

 # process config file

**Comment by NAUbackup** [comment]
I'm still perplexed about the  if (len(vm) > 1) issue. Maybe I should just use the same vm-list mechanism and not the session.xenapi.VM.get_by_name_label API call at all?

**Comment by thomasmck** [comment]
A concise way to just get the "real" VM with a particular name label would be:
``VM_ref = [x for x in session.xenapi.VM.get_by_name_label("<vm name>") if session.xenapi.VM.get_is_a_snapshot(x)][0]

**Comment by NAUbackup** [comment]
That's neat, Tom!
There still could be -- for whatever reason -- multiple VMs that had been given the same name-label, and that needs to be checked or one could be chosen and subsequently overwrite the directory holding the backups, since the directory is based on the name-label.
Best,
--Tobias

**Comment by thomasmck** [comment]
If there are multiple VMs then just remove the `[0]` bit and handle the list. This would actually be better as the '[0]` would cause an index error if there are no VMs with the specified name.

**Comment by NAUbackup** [comment]
Ah interesting, I will have to try that! ANd getting a null result for a VM name would be useful, as well.

**Comment by NAUbackup** [comment]
This is actually very fast and works well to trap any multiple VM names, for example:

vm, VM_ref= PRD-test ['OpaqueRef:e0f8b8ab-8ee3-03dc-8bf7-216ac7b96148', 'OpaqueRef:a6877710-6037-e067-009e-c0b67c4a5102']
vm, VM_ref= PRD-test ['OpaqueRef:e0f8b8ab-8ee3-03dc-8bf7-216ac7b96148', 'OpaqueRef:a6877710-6037-e067-009e-c0b67c4a5102']

I now get duplicate entries correctly listed when present and  It does successfully ignore snapshots.
I'll have to insert that check later in the code, though, as the session has to be first established before I can run the session.xenapi.VM.get_by_name_label command. I will work on this some more soon as I get a chance. Many thanks again, Tom!

**Comment by NAUbackup** [comment]
OK, I have this all pretty much working in a test environment now. Still doing some additional testing for QA.

**Comment by NAUbackup** [comment]
This will be taken care of in the next release.

**Comment by AlBundyLoves69** [comment]
When do you plan to publish +/- the next release?

**Comment by NAUbackup** [comment]
Hi, Peter. Good news -- I have now tagged the more recent releases, making it easier to download specific ones. Furthermore, there is also now a new branch for beta V3.23 that you can grab the code from directly right now and use -- at your own risk, of course, since this is obviously in progress. If you do try it out, please provide feedback!
