### ISSUE TITLE
Is it enough to keep only the .xva file?

### ISSUE THREAD

**Issue by VARGA-Peter** [NAUbackup/VmBackup#99]
I refer to the "Restore" section in your documentation https://github.com/NAUbackup/VmBackup#restore

My question: Is it enough to keep only the .xva file without the DISK-*, VIFs vm-metadata.xml directories/file in order to restore the VM correctly when I don't mind to keep the original uuid values or isn't a backup impossible without these additional information?

Thank you!

**Comment by NAUbackup** [comment]
Peter, the XVA file is self-contained. Should the whole pool have to be redone and the XVA imported, the metadata are then useful to identify various parameters that would not show up because of the hosts and pool information no longer matching. That said, the VM metadata is in fact embedded within the XVA file. For more about that, please see: https://xenserver.pl/citrix-xenserver/introduction-to-saving-vm-parameters-how-i-metadata-backup/10832
--Tobias

**Comment by VARGA-Peter** [comment]
Thank you Tobias!

**Comment by NAUbackup** [comment]
Sure thing, Peter!
